/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.nekixitodev.pjcapitulo1.pFormularios;

/**
 *
 * @author lenazu
 */
public class frmCapital extends javax.swing.JFrame {

    /**
     * Creates new form frmCapital
     */
    public frmCapital() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblMonto2 = new javax.swing.JLabel();
        lblMonto1 = new javax.swing.JLabel();
        lblMonto3 = new javax.swing.JLabel();
        txtMonto1 = new javax.swing.JTextField();
        txtMonto2 = new javax.swing.JTextField();
        txtMonto3 = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        lblMontoTotal = new javax.swing.JLabel();
        lblCapital = new javax.swing.JLabel();
        lblPorcenSocio1 = new javax.swing.JLabel();
        lblPorcenSocio2 = new javax.swing.JLabel();
        lblPorcenSocio3 = new javax.swing.JLabel();
        lblPorCantidadSocio1 = new javax.swing.JLabel();
        lblPorCantidadSocio2 = new javax.swing.JLabel();
        lblPorCantidadSocio3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setText("COOPERATIVA - MONTO DE CAPITAL");

        lblMonto2.setText("MONTO SOCIO 2");

        lblMonto1.setText("MONTO SOCIO 1");

        lblMonto3.setText("MONTO SOCIO 3");

        txtMonto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMonto1ActionPerformed(evt);
            }
        });

        txtMonto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMonto2ActionPerformed(evt);
            }
        });

        txtMonto3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMonto3ActionPerformed(evt);
            }
        });

        btnCalcular.setText("CALCULAR");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        lblMontoTotal.setText("MONTO TOTAL CAPITAL");

        lblCapital.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCapital.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCapital.setText("$0.0");

        lblPorcenSocio1.setText("PORCENTAJE SOCIO 1");

        lblPorcenSocio2.setText("PORCENTAJE SOCIO 2");

        lblPorcenSocio3.setText("PORCENTAJE SOCIO 3");

        lblPorCantidadSocio1.setText("0%");

        lblPorCantidadSocio2.setText("0%");

        lblPorCantidadSocio3.setText("0%");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(lblMonto2)
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMonto3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblPorcenSocio1)
                                    .addComponent(lblPorcenSocio3)
                                    .addComponent(lblPorcenSocio2))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(btnCalcular)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnLimpiar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblPorCantidadSocio3)
                                            .addComponent(lblPorCantidadSocio1)
                                            .addComponent(lblPorCantidadSocio2)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtMonto1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(230, 230, 230)
                                        .addComponent(lblTitulo))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtMonto2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(46, 46, 46)
                                        .addComponent(txtMonto3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(143, 143, 143))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblCapital, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblMontoTotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(69, 69, 69)
                    .addComponent(lblMonto1)
                    .addContainerGap(564, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblTitulo)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMonto3)
                    .addComponent(lblMonto2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMonto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMonto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMonto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcular)
                    .addComponent(btnLimpiar))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMontoTotal)
                    .addComponent(lblPorcenSocio1)
                    .addComponent(lblPorCantidadSocio1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCapital, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPorcenSocio2)
                        .addComponent(lblPorCantidadSocio2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPorcenSocio3)
                    .addComponent(lblPorCantidadSocio3))
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(74, 74, 74)
                    .addComponent(lblMonto1)
                    .addContainerGap(210, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMonto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMonto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMonto1ActionPerformed

    private void txtMonto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMonto2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMonto2ActionPerformed

    private void txtMonto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMonto3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMonto3ActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        
        //ENTRADA
        
        //Recuperando información del formulario
        double monto1 = Double.parseDouble(txtMonto1.getText());
        double monto2 = Double.parseDouble(txtMonto2.getText());
        double monto3 = Double.parseDouble(txtMonto3.getText());
        
        //PROCESO
        
        //Calculando el monto del capital
        double capital = monto1 + monto2 + monto3;
        
        //Calculando el porcentaje por monto
        double porcentaje1 = (monto1 * 100) / capital;
        double porcentaje2 = (monto2 * 100) / capital;
        double porcentaje3 = (monto3 * 100) / capital;
        
        //SALIDA
        
        //Imprimir los resultados
        lblCapital.setText("$ " + String.format("%.2f", capital));
        lblPorCantidadSocio1.setText(String.format("%.2f", porcentaje1) + "%");
        lblPorCantidadSocio2.setText(String.format("%.2f", porcentaje2) + "%");
        lblPorCantidadSocio3.setText(String.format("%.2f", porcentaje3) + "%");
        
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtMonto1.setText("");
        txtMonto2.setText("");
        txtMonto3.setText("");
        
        lblCapital.setText("$ 0.0");
        lblPorCantidadSocio1.setText("0%");
        lblPorCantidadSocio2.setText("0%");
        lblPorCantidadSocio3.setText("0%");
        
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCapital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCapital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCapital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCapital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCapital().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel lblCapital;
    private javax.swing.JLabel lblMonto1;
    private javax.swing.JLabel lblMonto2;
    private javax.swing.JLabel lblMonto3;
    private javax.swing.JLabel lblMontoTotal;
    private javax.swing.JLabel lblPorCantidadSocio1;
    private javax.swing.JLabel lblPorCantidadSocio2;
    private javax.swing.JLabel lblPorCantidadSocio3;
    private javax.swing.JLabel lblPorcenSocio1;
    private javax.swing.JLabel lblPorcenSocio2;
    private javax.swing.JLabel lblPorcenSocio3;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtMonto1;
    private javax.swing.JTextField txtMonto2;
    private javax.swing.JTextField txtMonto3;
    // End of variables declaration//GEN-END:variables
}
